### ISSUE TITLE
Permissions problem with --add-file

### ISSUE THREAD

**Issue by heyheydanhey** [create-dmg/create-dmg#101]
Hello!

I'm trying to create a keyboard layout installer dmg which includes a layout.bundle and a symlink to `~/Library/Keyboard Layouts`, for the former to be dropped into the latter.

I wish to add a link to `~/Library/Keyboard Layouts` via the `--add-file` option, but in the finished dmg it's not possible to drop the main file of the dmg into it. The crossed-out circle symbol appears. When I run create-dmg and it launches the dmg initially it works to drop the keyboard layout into it, but then after it closes on the message `Done running the AppleScript...` it no longer works - i guess this is a permissions issue?

I'm specifying the `--add-file` option like this: 
`--add-file Keyboard\ Layouts ~/Library/Keyboard\ Layouts 250 160`
Thanks in advance!

**Comment by heyheydanhey** [comment]
So to resolve my own issue.

I needed to manually create a symlink within the dmg source folder, as `--add-file` can't be used to do this. I would say that I think this would be a useful option to provide though! Thanks all good now I think.

**Comment by aonez** [comment]
@heyheydanhey is that symlink portable? Works with other usernames?

This remembers me to https://github.com/create-dmg/create-dmg/issues/54

**Comment by heyheydanhey** [comment]
Oh no

**Comment by aonez** [comment]
I've already tried creating a script for this at #54, but the quarantine flags make this script useless. Sadly no more ideas here.

**Comment by aonez** [comment]
If you find any workaround let us know in #54! Thanks @heyheydanhey!

**Comment by heyheydanhey** [comment]
Sorry one further idea if you don't mind - the bundle could go in `/Library/Keyboard Layouts/` rather than in the home dir `~/Library/Keyboard Layouts/`. Replacing the symlink to the former works as expected on my local computer (in the DMG a modal pops up asking for an admin password) but testing on another it won't ask for the password and won't drop in. That said, you can hit copy on the bundle and then paste over the Keyboard Layouts directory to get it to work! Any ideas why this might be?

**Comment by aonez** [comment]
You've used `--add-file "Keyboard Layouts" "/Library/Keyboard Layouts/" <x> <y>`?

**Comment by aonez** [comment]
This is probably caused by the Apple quarantine. I'm assuming you've downloaded the DMG to the other machine/user, so it has a quarantine applied and it refuses to ask for admin permission.

- Check for that flag with this: `xattr -l <DMG-PATH>`
- You can remove the quarantine like this: `xattr -cr <DMG-PATH>`

I think at this point you're out of luck using `create-dmg` for your purpose. Maybe creating a PKG (`pkgbuild`) is the way to go for you. Never built one but I think you can add some scripting there so you can also use `$HOME`. Let me know if that works for you!
