### ISSUE TITLE
Background is smaller than expected

### ISSUE THREAD

**Issue by Deuchnord** [create-dmg/create-dmg#102]
I'm creating a DMG file to distribute my app, but the image is shrunk to a very small size.

This is the command I'm invoking:
```bash
create-dmg --volname "Kosmorro installer" \
           --background build/distrib/darwin/dmg-background.jpg \
           --icon Kosmorro.app 100 100 \
           --window-size 640 320 \
           --app-drop-link 500 100 \
           $(distmacdmg) \
           dist/dmg
```

The created DMG archive looks like the following:

<img width="752" alt="Screenshot of the DMG file. The background is shrinked to a very small size in the top left corner." src="https://user-images.githubusercontent.com/7600265/91541905-52298e80-e91d-11ea-9c62-abb09264a84d.png">

The original `dmg-background.jpg` image dimensions are 1280 × 640. Everything else works as expected.

What am I missing?

**Comment by aonez** [comment]
Can you share the background or the DMG? I can only think of a retina issue, but your numbers feel ok...

**Comment by Deuchnord** [comment]
No problem, you can get them just here:

- [Background picture](https://drop.deuchnord.fr/r/BygnxZle#PL5BjXwEUrBgpO+1Y9QtMTsUdHuQkGlnHPzl9nsYxZM=)
- [DMG file](https://drop.deuchnord.fr/r/qsM0RhSm#BvmJJi9CdWUDH1ibB6K3cbmu/bDHjS0/UnE6+CPbAZk=)

**Comment by aonez** [comment]
Using a TIFF with the two sizes fixes the issue for you? I don't have a retina screen to test.

[Background.tiff.zip](https://github.com/create-dmg/create-dmg/files/5141295/Background.tiff.zip)

**Comment by aonez** [comment]
Forget that, the problem is the resolution of your image. It's 300 and it should be 72.

**Comment by aonez** [comment]
Anyway you can still create a TIFF containing both a 640x320 and a 1280x640 representations (both at 72 resolution) if you want it to show properly on retina and not retina displays.

[dmg-background.zip](https://github.com/create-dmg/create-dmg/files/5141343/dmg-background.zip)

**Comment by Deuchnord** [comment]
It works like a charm! Thanks!

**Comment by 9mm** [comment]
For anyone else looking how to make tiffs from pngs...

```
tiffutil -cathidpicheck background.png background@2x.png -out background.tiff
```

saved u some headache
