### ISSUE TITLE
syntax error: operand expected

### ISSUE THREAD

**Issue by Lohoris** [create-dmg/create-dmg#106]
I'm using 1.0.8 from brew, on macOS 10.14.6

I'm getting this error:

```
Gnaw:Lohoris ~/xx$ create-dmg pixp.app/ tgt/
Creating disk image...
........
created: /Users/Lohoris/xx/rw.pixp.app.dmg
du: /Users/Lohoris/xx/rw.pixp.app: No such file or directory
/usr/local/bin/create-dmg: line 253: ( * 512 / 1000 / 1000) + 1: syntax error: operand expected (error token is "* 512 / 1000 / 1000) + 1")
expr: syntax error
```

Please let me know if I can add anything useful for you to debug this.

**Comment by klartext79** [comment]
Same error here on macOS 11.0.1 (bigSur).
Installed with brew formula.

```
created: /Users/admin/workfolder/builds/myapp/_Latest/rw.myapp.app.dmg
du: /Users/admin/workfolder/builds/myapp/_Latest/rw.myapp.app: No such file or directory
/usr/local/bin/create-dmg: line 253: ( * 512 / 1000 / 1000) + 1: syntax error: operand expected (error token is "* 512 / 1000 / 1000) + 1")
expr: syntax error
```

**Comment by nsw42** [comment]
Having tripped over this too, I've investigated a bit. The first argument is supposed to be the output .dmg file. The create-dmg script invokes `hdiutil` to create (in the original report) rw.pixp.app, but `hdiutil` is adding a `.dmg` extension and creating `rw.pixp.app.dmg`.  Change the first argument when calling the script to have a `.dmg` suffix (e.g. `pixp.dmg`) and it all works fine.

**Comment by aonez** [comment]
How are you three calling the script?

**Comment by aonez** [comment]
You should call the script like this:

```sh
create-dmg <OPTION...> <DMG_PATH> <SOURCE_PATH>
```

Probably you're not specifying the `<DMG_PATH>` with a DMG extension.

**Comment by nsw42** [comment]
Certainly my issue was a n00b mistake, and once I corrected the extension, it's been working fine for me. I considered creating a pull request to detect and reject a missing .dmg extension - at least that way others making the same mistake will get an understandable error message.

**Comment by aonez** [comment]
That would be great @nsw42 👍🏼

**Comment by aonez** [comment]
Nice addition @nsw42 👍🏼
