### ISSUE TITLE
Keep getting regex errors

### ISSUE THREAD

**Issue by kakyoism** [create-dmg/create-dmg#111]
I'm a first-time user and I keep getting the following errors when running `create-dmg` command:

```sh
Unknown regexp modifier "/U" at -e line 1, at end of line
Can't find string terminator '"' anywhere before EOF at -e line 1.
```

My command in my shell script looks like this

```sh
    create-dmg \
	  --volname "My_Installer" \
	  --background "/path/to/my.png" \
	  --window-pos 200 120 \
	  --window-size 1020 600 \
	  --icon-size 100 \
	  --icon "/path/to/myapp.app" 200 190 \
	  --hide-extension "/path/to/myapp.app"\
	  --app-drop-link 600 185 \
	  --eula "/path/to/eula.txt" \
	  "$Installer" \
	  "$AppSrcDir"
```

My setup

- macOS 10.15.7
- create-dmg version: 1.0.8 from Homebrew

Where is the problem?

**Comment by kakyoism** [comment]
Solved it myself.

The problem is in the following options

```
--icon "/path/to/myapp.app" 200 190 \
--hide-extension "/path/to/myapp.app"\
```

These options expect a bundle name instead of a full path.
This could be made more clear in the documentation.

**Comment by aonez** [comment]
You can do it yourself
