### ISSUE TITLE
--volicon doesn't appear to work

### ISSUE THREAD

**Issue by mike-yoyo** [create-dmg/create-dmg#112]
When using the create-dmg script it works fine if I do the following:

`create-dmg "$dmg" "$src"`

However, if I attempt to add a volicon it falls over:

`create-dmg --volicon "icon.icns" "$dmg" "$src"`

As far as I can tell my generated 'icns' file is fine so I'm at a loss to what's going wrong.

**Comment by aonez** [comment]
Any output messages? Are all paths accesible?

**Comment by mike-yoyo** [comment]
Unfortunately no, no errors are output. I'll maybe update the script over the weekend and see if that magically fixes things for me.

**Comment by mike-yoyo** [comment]
Ok. I updated to the latest version of create-dmg - we were quite a bit out of date.

After a bit of fiddling around with my script (Which calls 'create-dmg') it seemed to work fine!
