### ISSUE TITLE
[Feature request] Retry the unmounting operation?

### ISSUE THREAD

**Issue by pzhlkj6612** [create-dmg/create-dmg#115]
Related to #114 .

Hi, thanks for your great work! Recently I encountered a ”resource busy“ error when using this tool in GitHub Actions workflow. Here is the log:

```
...
Done running the AppleScript...
Fixing permissions...
Done fixing permissions
Blessing started
Blessing finished
Unmounting disk image...
hdiutil: couldn't eject "disk2" - Resource busy
...
```

But I cannot reproduce it again:

```
...
Done running the AppleScript...
Fixing permissions...
Done fixing permissions
Blessing started
Blessing finished
Unmounting disk image...
"disk2" ejected.
Compressing disk image...
...
```

The code lines:

https://github.com/create-dmg/create-dmg/blob/121dbfac5ab5c0fde15c895b579130ca7dbfa95e/create-dmg#L407-L409

Could we wait a moment and try it again? I found something similar: https://github.com/LinusU/node-appdmg/pull/190 ( https://github.com/LinusU/node-appdmg/issues/142 and https://github.com/LinusU/node-appdmg/issues/161 )

I think a temporary `set +e` may be required since you set `set -e` on the top of the script.

Thank you for your time.

**Comment by pzhlkj6612** [comment]
As the manual page of `hdiutil` said:

> ERRORS
> 
>                                      ...                                  In
>      general, it tries to turn these error numbers into localized strings for
>      the user.  For background, intro(2) is a good explanation of our primary
>      error domain: the BSD errno values.                ...                The
>      following is a list of interesting errors that hdiutil can encounter:
> 
>      ...
> 
>      [EBUSY]            Resource busy.  Used if necessary exclusive access
>                         cannot be obtained.  This error often appears when a
>                         volume can't be unmounted.
> 
> from: https://ss64.com/osx/hdiutil.html

I looked up the code of "BSD errno":

https://github.com/apple/darwin-xnu/blob/8f02f2a044b9bb1ad951987ef5bab20ec9486310/bsd/sys/errno.h#L108 :

```c
#define EBUSY           16              /* Device / Resource busy */
```

https://github.com/freebsd/freebsd-src/blob/de1aa3dab23c06fec962a14da3e7b4755c5880cf/sys/sys/errno.h#L69 :

```c
#define	EBUSY		16		/* Device busy */
```

Therefore, I think it is sufficient to check whether the returned status code `$?` is `16` (compare with the code at https://github.com/LinusU/node-appdmg/blob/e1394d24b1be7799a3949ad0686cd9abb64339ee/lib/hdiutil.js#L67 ).

**Comment by aonez** [comment]
A PR with some unmount retries (maybe 2-3?) would be awesome @pzhlkj6612!
