### ISSUE TITLE
Codesigning option?

### ISSUE THREAD

**Issue by DavidJameson** [create-dmg/create-dmg#126]
Would be really nice if this tool included an option to let you sign the DMG after creation.

**Comment by aonez** [comment]
PRs are welcome :)

**Comment by aonez** [comment]
Went ahead and implemented this one. https://github.com/create-dmg/create-dmg/commit/dfc94c3cd592a4515bed7651cea786ed4b1c7d36

**Comment by DanilKorotenko** [comment]
So the issue can be considered as closed?

**Comment by aonez** [comment]
Probably I should release this now and close the issue.

**Comment by aonez** [comment]
Released!
