### ISSUE TITLE
Script fails with macOS 12.3 on Apple Silicon due to "bless" option not supported

### ISSUE THREAD

**Issue by Phillipus** [create-dmg/create-dmg#127]
Since macOS 12.3 on Apple Silicon the "bless" part of the script gives the following error and the script fails:

`bless: The 'openfolder' is not supported on Apple Silicon devices.`

Commenting out this line succeeds:

`bless --folder "${MOUNT_DIR}" --openfolder "${MOUNT_DIR}"`

**Comment by aonez** [comment]
Please attach the output of `bless --help`.

It works on 12.2.1 so maybe they removed that option it the 12.3 beta.

**Comment by Phillipus** [comment]
> Please attach the output of bless --help.

That doesn't help much as all options are listed.

However `man bless` shows a different set of options for Intel and a different set of options for Silicon. `--openfolder` is not an option listed for Silicon.

**Comment by aonez** [comment]
I'm updating to 12.3 to test that one. Just checked that not using that option does not seem to affect on the DMG opening in the Finder when mounted.

Will test tomorrow on older OSs and if not using that argument does not affect on most OSs maybe we can get rid of it instead of detecting  Silicon and limiting to Intel or 12.2.1-.

**Comment by Phillipus** [comment]
I tested with the whole line removed and also with the offending part removed:

`bless --folder "${MOUNT_DIR}"`

In both cases it _seemed_ to be OK.

**Comment by aonez** [comment]
> In both cases it _seemed_ to be OK.

Indeed! Tested it in as low as Mac OS X 10.6. So maybe that bless was only needed in older OSs.

Probably then the best way is to set the bless step as optional and not used by default.

**Comment by Aleksid1** [comment]
I have the same problem after upgrading to macOS 12.3 on Mac Mini M1.

**Comment by Aleksid1** [comment]
Suggested change to remove "bless --folder ... " line cures the problem.

**Comment by aonez** [comment]
Just released 1.0.10 with this issue fixed: https://github.com/create-dmg/create-dmg/releases/tag/v1.0.10
Also the brew update is on it's way: https://github.com/Homebrew/homebrew-core/pull/97089

**Comment by Phillipus** [comment]
Thanks for the fast response. 👍
