### ISSUE TITLE
Problem with notarization

### ISSUE THREAD

**Issue by StefanPatman** [create-dmg/create-dmg#131]
I was trying to notarize a disk image created by this tool, including only a signed app bundle and a link to `/Applications`. However, notarization would always fail, with `notarytool` reporting that the signature for the main binary was invalid. No other errors were reported. I did not face this issue when notarizing images created using `hdiutil`.

I presume that `create-dmg` is somehow altering the main executable within app bundles. Is there a way to prevent this?

**Comment by aonez** [comment]
Can you share the command you're using? I've only signed DMGs, never notarized them.

**Comment by aonez** [comment]
Just did a test and worked properly, the package "Keka-1.2.53.dmg" was created using `create-dmg`:

```
aone@aONe-M1 ~ % xcrun notarytool submit "/Users/aone/Desktop/Keka-1.2.53.dmg" --keychain-profile "AC_PASSWORD" --wait 
Conducting pre-submission checks for Keka-1.2.53.dmg and initiating connection to the Apple notary service...
Submission ID received
  id: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
Successfully uploaded file35,1 MB of 35,1 MB)   
  id: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
  path: /Users/aone/Desktop/Keka-1.2.53.dmg
Waiting for processing to complete.
Current status: Accepted.............
Processing complete
  id: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
  status: Accepted
aone@aONe-M1 ~ % xcrun stapler staple /Users/aone/Desktop/Keka-1.2.53.dmg 
Processing: /Users/aone/Desktop/Keka-1.2.53.dmg
Processing: /Users/aone/Desktop/Keka-1.2.53.dmg
The staple and validate action worked!
aone@aONe-M1 ~ % xcrun stapler validate /Users/aone/Desktop/Keka-1.2.53.dmg 
Processing: /Users/aone/Desktop/Keka-1.2.53.dmg
The validate action worked!
aone@aONe-M1 ~ % xcrun stapler validate /Volumes/Keka/Keka.app 
Processing: /Volumes/Keka/Keka.app
The validate action worked!
aone@aONe-M1 ~ % 
```

Followed the instructions here:
https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow

**Comment by aonez** [comment]
I went ahead and added notarization support in `create-dmg` using `--notarization <credentials>` where the credentials should be generated using [Apple's recommendation](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow):

```
% xcrun notarytool store-credentials "AC_PASSWORD"
               --apple-id "AC_USERNAME"
               --team-id <WWDRTeamID>
               --password <secret_2FA_password>
```

**Comment by StefanPatman** [comment]
Thanks for adding the notarization option.

I had another look and the issue only appears when I prepare the scripts _source_folder_, only if I move the files _after_ signing. I am not sure how this should affect anything, since `hdiutil` works fine even in this case.

Here's a minimal example for reproduction. I am using Python 3.9.12 (universal2 release) and a pip installed PyInstaller. If I instead codesign after copying the app bundle, everything works as expected.
```
echo "print(42)" > test.py
pyinstaller -w test.py
codesign -v --deep --force --options=runtime --sign $CODESIGN_ID --timestamp dist/test.app
mkdir dist/dmg
cp -r dist/test.app dist/dmg/
create-dmg --codesign $CODESIGN_ID --notarize AC_PASSWORD test.dmg dist
```
Notarization then fails with the following log:
```
  "issues": [
    {
      "severity": "error",
      "code": null,
      "path": "test.dmg/test.app/Contents/MacOS/test",
      "message": "The signature of the binary is invalid.",
      "docUrl": null,
      "architecture": "arm64"
    }
```

I suppose this is not as serious as I initially thought, but it still seems like a bizarre behaviour.
