### ISSUE TITLE
Codesign struggles

### ISSUE THREAD

**Issue by Willy-JL** [create-dmg/create-dmg#142]
I'll preface this by saying that it's not an issue in having with this fantastic piece of software per se, but rather a problem I'm facing with DMGs in general that is still present when using this to create them. I've been struggling with this for a week now, I'm not a daily macOS user and this might just be due to my lack of understanding so please bear with me and I'm sorry for invading this issue section.

This is a Python app that I'm trying to package. When running it from source it works perfectly fine but installing the requirements needs some development packages installed (XCode I think?) and takes upwards of 20 minutes so I'd like to package my app with all its requirements as a "binary".

I'm doing this easily with cx_Freeze which produces a .app which works mostly fine. I had some issues because the bundle included some empty files which codesign didn't like, so after removing it I was able to self sign the app bundle. One peculiar issue I have is that it refuses to run in .app format when not inside /Applications, while running the executable itself in .app/Contents/MacOS works fine anywhere on the system. This annoys me but I figured the next best thing would be to setup a DMG.

So I did that, both manually and using this script and both work fine as DMGs, my issue is instead that every time I package the .app as a DMG it invalidates the code signing on the app itself for some reason, so opening it will say that it is damaged and should be moved to the trash.

Am I doing something wrong?

**Comment by Benitoite** [comment]
I suggest digesting some of these basic Apple macOS developer documents.  All your answers will come through understanding these.  We can't see your product, so we can't judge your wrongness.

- [ ] [Bundles](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/AboutBundles/AboutBundles.html)
- [ ] [Codesigning](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html#//apple_ref/doc/uid/TP40005929-CH4-SW2)
- [ ] [Information Property List](https://developer.apple.com/documentation/bundleresources/information_property_list)
- [ ] [Entitlements](https://developer.apple.com/documentation/bundleresources/entitlements)
- [ ] [Embedding Non-standard Code Structures](https://developer.apple.com/documentation/xcode/embedding-nonstandard-code-structures-in-a-bundle)

**Comment by Willy-JL** [comment]
Thanks for those, turns out my main issue with the .app not working outside /Applications was an issue with Python trying to write to stdout and stderr when .app bundles don't get them. As to why it worked in /Applications I'm guessing that maybe they get some special log file so they actually do have std streams. Either way that was the only reason I wanted to setup a DMG so now I don't have this problem anymore. Thanks either way!
