### ISSUE TITLE
Universal binary

### ISSUE THREAD

**Issue by davidbannon** [create-dmg/create-dmg#158]
Hi Folks, I use create-dmg to package an open source app called tomboy-ng. All good. 

However, its now possible for me to make a Universal Binary for the app, one that runs on x86_64 and aarch64. It seems to work while testing, I can open the app package I make using the universal binary and the app runs on my x86_64 box. (No, I have not tested it on an Apple Silicon box yet).

But if I make a dmg installer using that universal binary, my Monterey system tells me its "Missing some component". Rebuild the dmg using a x86_64 binary and all is good.

Any suggestions ?  Or should I just make two packages and leave this universal binary idea for people who know what they are doing ?

(Me ? Unix/Linux user from way back, terribly inexperienced Mac user.)

Davo

**Comment by aonez** [comment]
Hi Davo,

I make packages from universal apps with no issues, so the problem should
be in the app itself or in and intermediate step. There’s any chance you
can share that dmg?

**Comment by davidbannon** [comment]
Thanks AOnez, I am grateful. However (and this is really embarrassing) "the problem has gone away".
I have no idea how, the package process is all scripted so I must be doing the same thing as I did yesterday. 

Only thing different this morning is that I have restarted the machine, I installed create-dmg yesterday on a new, to me, box and immediately ran my package script using a binaries built a little earlier. My scripts overwrite an existing package so I needed to make a new one to show you this morning. But I used yesterday's binaries so all that happened today is the lipo stage to make the universal binary and the packaging.

Sigh....

Anyway, the package appears to meet with my Intel based Monterey box's approval, I will have to wait for feed back from an Apple Silicon user to be sure but the problem I was experiencing is gone. By the way, my package is now at 

https://github.com/tomboy-notes/tomboy-ng/releases/download/v0.36c/tomboy-ng64_0.36g_UNI.dmg 

Thanks again for your offer to help.
David

**Comment by aonez** [comment]
@davidbannon both the dmg the app open without a problem on my side,  silicon here. The only thing I found is that it's not signed nor notarized, but I suppose your users already know that.

**Comment by davidbannon** [comment]
Yes Aonez, so far my mac users put up with lack of signing. Its far a traditional Mac app and the only Mac user are cross platform people I expect. Not that many compared to Windows and Linux.
Thanks for confirming no other problem with the packaging, that's great news !
I'll close this now.
David
