### ISSUE TITLE
usage: dirname path

### ISSUE THREAD

**Issue by jacktasia** [create-dmg/create-dmg#16]
Howdy,

I was following your "sample" file template and I kept getting "usage: dirname path" ..after looking at the source I tracked it down to how `AUX_PATH` was being set.

When I changed it to this:

`AUX_PATH="$( cd "$( dirname "$0" )" && pwd )/support"`

everything worked as expected. I am no bash expert so I don't know if this change should actually be committed but I thought it was worth mentioning.

That said, this is a very nice, and useful, project.

**Comment by apjanke** [comment]
This has been fixed. The `AUX_PATH` is now being set with the following:

```bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
[...]
AUX_PATH="$SCRIPT_DIR/support"
```
