### ISSUE TITLE
Unknown option: --custom-icon. Run 'create-dmg --help' for help.

### ISSUE THREAD

**Issue by yyt231** [create-dmg/create-dmg#167]
version 1.2.0 and 1.2.1 
Unknown option: --custom-icon. Run 'create-dmg --help' for help.

(base) tony@yangyantaodeMacBook-Pro ~/建站/软件 » sudo create-dmg --volname "PDF Converter by Flyingbee" \
                    --window-pos 200 120 \
                    --window-size 800 400 \
                    --volicon "/Users/Tony/建站/软件/mac_soft/PDF Converter by Flyingbee.app/Contents/Resources/AppIcon.icns" \
                    --icon-size 100 \
                    --icon PDF_Converter_by_Flyingbee.app 200 190 \
                    --hide-extension "PDF Converter by Flyingbee.app" \
                    --custom-icon "/Users/Tony/建站/图标/arrow.png" 600 185 \
                    --app-drop-link 600 185 \
                    "PDF_Converter_by_Flyingbee.dmg" \
                    "/Users/Tony/建站/软件/mac_soft/PDF Converter by Flyingbee.app"
Unknown option: --custom-icon. Run 'create-dmg --help' for help.

**Comment by aonez** [comment]
That option was removed a few years ago.
