### ISSUE TITLE
`ln -s /Applications /Volume/..`  fails: No such file or directory

### ISSUE THREAD

**Issue by aaronyuai** [create-dmg/create-dmg#169]
When app bundle is 100MB (a minimal UI I used for testing), create-dmg does not have any problem
When app bundle is 2GB, `ln -s /Applications` fails with this error  message:
Making link to Applications dir...
/Volumes/dmg.Czwp56
ln:
/Volumes/dmg.Czwp56/Applications: No such file or directory

After the script fails, `ls /Volumes/dmg.Czwp56` shows only app bundle,
`ln -s /Applications /Volumes/dmg.Czwp56/Applications` works without problem

I edited create-dmg script directly, and replace the ln with `ln -s /Applications /Users/XXX/test_app`
this command fails as well

So is this problem with Mac?
or because of large file?

**Comment by aaronyuai** [comment]
I did some more investigation:

1. If I remove significant part of contents to make the total package under 2GB, create-dmg succeeds
2. in the same run, `ln -s /Applications /tmp/test_app` works, but `ln -s /Applications $MOUNT_DIR/Applications` fails

create-dmg is under /opt/homebrew
so I suspect it's because the script and the volume are in different partition when .dmg is too large

**Comment by aaronyuai** [comment]
by adding --sandbox-safe, and make changes from `ln -s /Applications /private/tmp/dmg.XXXX/Applications` to `ln -s /Applications /tmp/dmg.XXXX/Applications`, this error passes

and next error `cp: /tmp/dmg.YnIA53/.VolumeIcon.icns: No such file or directory`

This should be the same root reason as the earlier one.

**Comment by aaronyuai** [comment]
ok. figure it out, it's because $MOUNT_DIR somehow has a heading '\n' that breaks all filepaths.

**Comment by ELowry** [comment]
When trying to build my DMG, I'm getting the following error:
```
Mounting disk image...
Device name:  /dev/disk2
Searching for mounted interstitial disk image using /dev/doisk2s...
Moint dir:
/Volumes/dmg.OGcdL1
Making link to Applications dir...
/Volumes/dmg.OGcdL1
ln:
/Volumes/dmg.OGcdL1/Applications: No such file or directory```

I'm not totally sure, but I'm guessing that this is the same issue? Right?

**Comment by aaronyuai** [comment]
> When trying to build my DMG, I'm getting the following error:
> 
> ```
> Mounting disk image...
> Device name:  /dev/disk2
> Searching for mounted interstitial disk image using /dev/doisk2s...
> Moint dir:
> /Volumes/dmg.OGcdL1
> Making link to Applications dir...
> /Volumes/dmg.OGcdL1
> ln:
> /Volumes/dmg.OGcdL1/Applications: No such file or directory
> ```
> 
> I'm not totally sure, but I'm guessing that this is the same issue? Right?
> 
> If so, is there a way for me to get the fix? I've only ever installed this via brew, and am not too familiar with how I'd go about building/installing my own version.

exactly, 
`ln:
/Volumes/dmg.OGcdL1/Applications:`
should be:
 `ln: /Volumes/dmg.OGcdL1/Applications:`

**Comment by silicooon** [comment]
Fall into this error too.. the thing I am trying to pack is 4.8gb.
Should I change something on the executable myself?

**Comment by aonez** [comment]
@silicooon I've just merged the fix from @aaronyuai #170, can you update your create-dmg script with the one in the repo and check if your issue is fixed:

https://github.com/create-dmg/create-dmg/blob/master/create-dmg

**Comment by silicooon** [comment]
@aonez THANK YOU! that was really fast. 

Can you please check my oneliner here and let me know if something is wrong? I need to only point to an app?

`create-dmg --volname "MyGreat App v1.1.0" --volicon "/Volumes/falcon/upload/MyGreat App v1.1.0/MyGreat App.app/Contents/Resources/Icon.icns" --icon "/Volumes/falcon/upload/MyGreat App v1.1.0/MyGreat App.app" 182 190 --icon-size 100 --app-drop-link 462 190 --hdiutil-quiet --window-pos 200 120 --window-size 660 453 --background /Users/user/Documents/bgs/a14d52sc1e970.png --no-internet-enable /Volumes/falcon/upload/MyGreatApp.v1.1.0.dmg /Volumes/falcon/upload/MyGreat\ App\ v1.1.0`

**Comment by silicooon** [comment]
Okay! It seems when I am using the script with full paths it always errors like this:
`Creating disk image...
Mounting disk image...
Device name:     /dev/disk26
Searching for mounted interstitial disk image using /dev/disk26s...
Mount dir:       /Volumes/dmg.uqtqYY
Copying background file '/Volumes/falcon/upload/BigAppv1.1.0/bigapp.png'...
Copying volume icon file '/Volumes/falcon/upload/BigAppv1.1.0/bigapp.icns'...
Unknown regexp modifier "/V" at -e line 1, at end of line
Regexp modifiers "/l" and "/u" are mutually exclusive at -e line 1, at end of line
Can't find string terminator '"' anywhere before EOF at -e line 1.`

But if I run it into my current directory all is fine.

`create-dmg --volname "BigApp_v110" --icon "BigApp.app" 182 190 --icon-size 100 --hdiutil-quiet --background BigApp_1521970.png --no-internet-enable BigApp.dmg BigApp.app`

**Comment by aonez** [comment]
@silicooon does using " in all the paths fix the issue for you?

```sh
create-dmg --volname "MyGreat App v1.1.0" --volicon "/Volumes/falcon/upload/MyGreat App v1.1.0/MyGreat App.app/Contents/Resources/Icon.icns" --icon "/Volumes/falcon/upload/MyGreat App v1.1.0/MyGreat App.app" 182 190 --icon-size 100 --app-drop-link 462 190 --hdiutil-quiet --window-pos 200 120 --window-size 660 453 --background "/Users/user/Documents/bgs/a14d52sc1e970.png" --no-internet-enable "/Volumes/falcon/upload/MyGreatApp.v1.1.0.dmg" "/Volumes/falcon/upload/MyGreat App v1.1.0"
```

**Comment by silicooon** [comment]
No, i have tried that too. :( Thank you!

**Comment by austinulfers** [comment]
Had this same issue, modifying the script directly resolved it for me as well.

**Comment by aonez** [comment]
Please check the new release: https://github.com/create-dmg/create-dmg/releases/tag/v1.2.2
