### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by aonez** [create-dmg/create-dmg#60]
Maybe @andreyvit you can add some of the forkers rights to maintain this repo, since is still used by lots of people.

Thanks for your time :)

**Comment by aonez** [comment]
Now I seen that:

> Starting in January 2015, everyone who gets a pull request merged gets commit access to the repository.

But no pull request is accepted since 2016...

**Comment by u-foka** [comment]
Yeah, I did a small fix that was fixed for my project and contributed it back, so now I have the commit access for example, but sadly have no time to test and review the PRs to accept them :/

**Comment by aonez** [comment]
Thanks for the reply @u-foka! Great name by the way 😂

**Comment by andreyvit** [comment]
Oops, sorry guys. Lemme look at that.

**Comment by andreyvit** [comment]
All right, this project is officially looking for a new maintainer. I've merged a bunch of PRs that could be merged cleanly, and invited authors to consider being a maintainer.

If someone's interested in maintanining create-dmg, please let me know in https://gitter.im/create-dmg/Lobby.

**Comment by apjanke** [comment]
Another create-dmg user here. Over at https://octave-app.org we're maintaining a fork of create-dmg for our internal use (https://github.com/octave-app/create-dmg). I'd be happy to be a contributor and try to get our changes back upstream. Don't know that I have the spare time to be a core maintainer, though.

**Comment by aonez** [comment]
@apjanke just feel free to push some pull requests, you'll then have commit access :)

Seeing that you are familiar with brew, maybe you can also help here:
https://github.com/Homebrew/homebrew-core/pull/45310

**Comment by apjanke** [comment]
That Homebrew/homebrew-core#45310 is a Catalina issue, and I don't have a Catalina box set up yet. (I'm not upgrading my main boxes to Catalina, because it breaks Aperture.) I'll have one set up soon because I need to test Octave on it though, and when I do, maybe I can help out there.

**Comment by apjanke** [comment]
I suggest maybe if this is going to be a multi-maintainer project and @andreyvit doesn't want to be the primary owner any more, this project could be moved under a newly-created GitHub Organization? That makes multi-owner projects easier to work with.

**Comment by aonez** [comment]
> Catalina, because it breaks Aperture

I might skip Catalina as my main OS as well (although having a VM since the first betas to test). Maybe for your issue you can check [Retroactive](https://github.com/cormiertyshawn895/Retroactive).

**Comment by apjanke** [comment]
> Maybe for your issue you can check Retroactive.

Nope. Photography is a serious hobby for me, and I ain't using no not-officially-supported third-party shit for it. I'm sticking with Mojave for the next three years or so. :)

**Comment by andreyvit** [comment]
@apjanke I don’t mind moving to an org, but what is an advantage of that?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by apjanke** [comment]
Making it an org allows you to add other maintainers who themselves have the rights to add new Contributors etc. Keeping it as a personal repo means that you'll have to do all the personnel permissioning yourself. (I think they'll also have rights to change settings like Issues and Wiki availability.) It's just a minor reduction in admin work for you.

Also as an org, the list of contributors & admins (group members) will be public, which might be helpful for people who are looking for contacts.

That's all that I know of. Not a big deal.

**Comment by andreyvit** [comment]
Okay guys, so there's been a lot of discussion here, and we didn't decide anything. So let's try to make a decision. @apjanke Do you want to be the maintainer? I'm ready to create an org and move the repo over, but I want someone in charge first.

**Comment by apjanke** [comment]
You know what, sure. I'll be the maintainer. I looked over the issue volume here, and that's something I can take on, especially since I'm going to be working with create-dmg for Octave.app anyway.

**Comment by digarok** [comment]
Feel free to add me to the new project as a developer.  You can see my comments on the AppleScript permissions issue and I'd like to get that and some other things cleaned up since this appears to be the canonical way to package DMGs.

**Comment by andreyvit** [comment]
Thank you, guys! @apjanke You're invited as an owner to the new org. @digarok You're invited as a member. There's a whole bunch of other existing contributors to this repo, but I'll let @apjanke decide on whom else to give what sort of permissions. I'll move the repo now.

**Comment by andreyvit** [comment]
Actually I've also invited @aonez since he's been listed as the primary helping hand so far, and in fact created this issue.

So it's official: @apjanke, you're the new maintainer of create-dmg. Feel free to rule with an iron fist or a light touch. If you need anything or if I forgot to transfer something (perhaps Gitter room?), please message me. I'll leave it to you to update the README as you see fit.

**Comment by apjanke** [comment]
Sounds good! I should have some time to update the docs this weekend.

**Comment by apjanke** [comment]
I've [updated the README](https://github.com/create-dmg/create-dmg/commit/13987fad78a35d6496143057f5926c0e8db7ed4a) to reflect my taking over as maintainer. (@andreyvit, let me know if you'd like to be credited differently in the "Status and contribution policy" section.)

Over the next couple weeks I will be reviewing all the outstanding Issues and seeing which can be fixed or closed out. Please be patient as I get up to speed here.

**Comment by apjanke** [comment]
I'm going to do most of my initial changes as PRs with review requests out to the other maintainers until I get more familiar with the code. Let me know if this is too much work for you.

**Comment by apjanke** [comment]
I've completed my issue review and done a small 1.0.8 release, which should take care of the previous problems with getting the new versions into Homebrew. See https://github.com/Homebrew/homebrew-core/pull/55413.
