### ISSUE TITLE
Update dmg-license.py

### ISSUE THREAD

**Issue by aonez** [create-dmg/create-dmg#78]
https://bitbucket.org/jaredhobbs/pyhacker/src/master/licenseDMG.py

**Comment by apjanke** [comment]
I requested that pyhacker add an explicit LICENSE file to make sure it's cool we're using and redistributing their script: https://bitbucket.org/jaredhobbs/pyhacker/issues/3/license.

**Comment by aonez** [comment]
I'm sure [he already knows](https://bitbucket.org/jaredhobbs/pyhacker/issues/2/check-default-rez-path), but that would be great.

**Comment by aonez** [comment]
> it's cool we're using and redistributing their script

I was searching for this https://github.com/andreyvit/create-dmg/pull/47#issuecomment-542262196, that he wrote :)

**Comment by apjanke** [comment]
Okey dokey. Guess it's time to pull in the new version. I'll see if I can find time later tonight.

**Comment by apjanke** [comment]
PR for updating the dmg-license script:  #98
