### ISSUE TITLE
macOS Catalina scrollbar glitches

### ISSUE THREAD

**Issue by ijanos** [create-dmg/create-dmg#91]
I am seeing a weird green line next to the scrollbar when a second monitor is attached on macOS 10.15 (Catalina). 

<img width="758" alt="Screenshot 2020-02-10 at 13 04 49" src="https://user-images.githubusercontent.com/175447/74148581-0ecc3480-4c06-11ea-8b6b-7377396b3dcc.png">

**Comment by apjanke** [comment]
Adding "help wanted" because I have no idea what could cause this or what to do about it.

**Comment by aonez** [comment]
@ijanos you should probably report this to Apple since that license GUI is not custom.

**Comment by apjanke** [comment]
Yeah. I'm going to close this out as WontFix/Upstream because I don't think there's _anything_ we can do about this; that's a system dialog widget that we're just delegating to. Sounds like a macOS bug. Sorry! And thanks for reporting.

**Comment by ijanos** [comment]
No worries, I didn't realize it is a system dialog. Cheers!

**Comment by ijanos** [comment]
It is fixed in Big Sur.

**Comment by apjanke** [comment]
Yay!
