### ISSUE TITLE
Determine minimum macOS version requirement

### ISSUE THREAD

**Issue by apjanke** [create-dmg/create-dmg#95]
We should document the earliest version of macOS that is supported by create-dmg.

As of now; I don't know what that is. It probably depends on just the version of bash shipped with macOS, and since we're not doing anything fancy, it probably works on quite old versions.

**Comment by aonez** [comment]
I can test up to 10.6, if needed.

**Comment by apjanke** [comment]
> I can test up to 10.6, if needed.

Sweet! Could you do that against the current state of the repo? 10.6 is super old by Mac standards, and it would be nice if we could establish that we still work against that.

**Comment by aonez** [comment]
Just tested and works as expected in 10.6 Snow Leopard ❤️! The only requirement is to have developer tools installed. Probably it will work in 10.5 but I don't have a VM at hand to test.

**Comment by apjanke** [comment]
Updated the README to reflect this: https://github.com/create-dmg/create-dmg/commit/e1817c0d898e024d1ca1e70a7477615b36f15cd8. Let me know if you disagree with the content or wording.

Thank you for testing this! I don't have anything that'll run earlier than 10.11.

Closing as Fixed.

**Comment by aonez** [comment]
> I don't have anything that'll run earlier than 10.11

[Parallels](https://www.parallels.com) makes is easy :)

![Screenshot 2020-06-16 at 12 46 49](https://user-images.githubusercontent.com/480163/84765484-91f40180-afcf-11ea-83b3-4685e99e6596.png)

**Comment by apjanke** [comment]
Dude, you're a better Mac sysadmin than I am. I have Parallels, VMware Fusion, and VirtualBox, and I can't get any guest VMs older than 10.12 to boot reliably in any of them. :( :( :(

**Comment by aonez** [comment]
> VMware Fusion, and VirtualBox

Those are tricky indeed... some hack needed. But Parallels is pretty straightforward! Just drop the `Mac OS X * Installer.app` in the assistant and it's all done automagically. No *hackintoshing* needed.

**Comment by apjanke** [comment]
Maybe I need to try that again. Thanks for the tip.

**Comment by apjanke** [comment]
:( :( :(

<img width="1003" alt="Screen Shot 2020-06-17 at 2 14 34 PM" src="https://user-images.githubusercontent.com/2618447/85003881-d47b2280-b124-11ea-880c-2348e3bb1f81.png">

**Comment by aonez** [comment]
Odd... You've used the wizard just dropping the `Installer.app`?

**Comment by apjanke** [comment]
Yup. Pulled out my old copy of the installer, drag-and-drop onto Parallels' wizard, and chose all the defaults. :/

**Comment by aonez** [comment]
Maybe you should [re-download the installer](https://support.apple.com/en-us/HT206886) since there was a certificate that expired for Apple, maybe that's your problem right now.

**Comment by apjanke** [comment]
Sounds like you're on the right track with the diagnosis. I downloaded the El Capitan installer from that link, though, and it's a .dmg file with a .pkg inside it, and it doesn't seem like either Parallels or VMware Fusion know what to do with that. Looks like an installer that can only be run from within an existing install of an older version of OS X?

**Comment by aonez** [comment]
That pkg [should contain the installer app](https://support.apple.com/en-gb/HT201372), just install it (will expand the app in your Applications folder) or extract it:

> OS X El Capitan
El Capitan downloads as a disk image. On a Mac that is compatible with El Capitan, open the disk image and run the installer within, named InstallMacOSX.pkg. It installs an app named Install OS X El Capitan into your Applications folder. You will create the bootable installer from this app, not from the disk image or .pkg installer.

**Comment by apjanke** [comment]
Ooooooh... okay, lemme try that.

**Comment by aonez** [comment]
Menawhile... Not sure if I should call it 11.0 or 10.16.

![Screenshot 2020-06-23 at 14 01 37](https://user-images.githubusercontent.com/480163/85401321-1e676c80-b55a-11ea-9848-cd54a49d50dd.png)

**Comment by apjanke** [comment]
Big shot early adopter here! ;)

I'm still on 10.14.6. I use Aperture, and 10.15 broke it, and basically every game on Steam.

**Comment by aonez** [comment]
Just trying it in Parallels, only one Mac in my hands can't risk to break it with an early beta 🤪

![Screenshot 2020-06-23 at 14 58 55](https://user-images.githubusercontent.com/480163/85406625-5d99bb80-b562-11ea-8b78-1679216698b9.png)

**Comment by apjanke** [comment]
Yeah, I oughtta be doing the same thing to make sure Octave.app isn't broken under Big Sur. Sigh. There goes another few hours of my life. :)
