### ISSUE TITLE
hdiutil: create failed - Resource busy

### ISSUE THREAD

**Issue by bmolyneaux** [create-dmg/create-dmg#99]
I recently upgraded to Catalina and now see this failure when I run create-dmg:

```
Creating disk image...
....................................................................................................................................
hdiutil: create failed - Resource busy
```

**Comment by bmolyneaux** [comment]
I added `--hdiutil-verbose` and got some more info (I renamed the paths):


```
2020-06-17 16:59:59.814 copy-helper[2963:27976] About to copy "/path/to/My.app".
................................................................................................................2020-06-17 17:00:02.196 copy-helper[2963:27976] Copy finished.
....................



detachTempimageFile: synchronous unmount /dev/disk2s1 returned 49168
retrying unmount (#1)...
detachTempImageFile: synchronous retry (#1) unmount /Volumes/MyApp (/dev/disk2s1) returned 49168
retrying unmount (#2)...
detachTempImageFile: synchronous retry (#1) unmount /Volumes/MyApp (/dev/disk2s1) returned 49168
retrying unmount (#3)...
detachTempImageFile: synchronous retry (#1) unmount /Volumes/MyApp (/dev/disk2s1) returned 49168
Finishing…
2020-06-17 17:00:03.821 diskimages-helper[2947:27939] -processKernelRequest: flush received
2020-06-17 17:00:03.959 diskimages-helper[2947:27939] -processKernelRequest: flush received
2020-06-17 17:00:03.969 diskimages-helper[2947:27901] *useEffectiveIDs**** euid/egid changed to 343541,89939 (uid/gid is 343541,89939)
DIHLDiskImageCreate() returned 49168
hdiutil: create: returning 49168
hdiutil: create failed - Resource busy
```

**Comment by aonez** [comment]
Maybe you have an already mounted `MyApp` volume?

**Comment by bmolyneaux** [comment]
I made sure that I had no mounted volumes before running the script. I also tried restarting my computer a couple of times.

I ended up just delegating the dmg creation to another member of my team since it still works on his machine (he is still on Mojave).

**Comment by bmolyneaux** [comment]
I tried running the same command again today, but with success! I ended up with a working dmg, but the following was printed at the end:
`hdiutil: internet-enable: verb not recognized`
Of course, adding `--no-internet-enable` resolves that issue.

**Comment by Wohlstand** [comment]
Right now, I do have absolutely same error, on macOS 13, on GitHub Actions CI:
https://github.com/WohlSoft/Moondust-Project/actions/runs/13387610179/job/37387737056

I ran command next:
```
"./create-dmg.sh"
        --volname "Moondust Project Development Kit"
        --window-size 800 600
        --app-drop-link 450 320
        --subfolder-name "Moondust Project"
        --no-internet-enable
        "${CMAKE_INSTALL_PREFIX}/pge-project-${PACKAGE_SUFFIX}-macosx.dmg"
        "${CMAKE_INSTALL_PREFIX}/${PGE_INSTALL_DIRECTORY}/"
```
(from the CMake itself)
P.S. the "--subfolder-name" is my custom argument I added for my own needs, I going to contribute it.

The fact: local build just works (I have macOS-15 right now, on M2), but on CI it fails with the same error.
